"""Local release readiness manifest generation."""

from __future__ import annotations

import subprocess
from pathlib import Path

from coductor.artifacts.models import (
    ArtifactEnvelope,
    ArtifactInput,
    EvidenceBundleData,
    Producer,
    ReleaseGitState,
    ReleaseManifestData,
    ReleaseSafety,
)
from coductor.artifacts.repository import ArtifactRepository
from coductor.domain.enums import ArtifactStatus, ArtifactType, ProducerKind
from coductor.domain.ids import new_id
from coductor.services.run_service import utc_now
from coductor.storage.database import Database
from coductor.workflow.artifact_writer import WorkflowArtifactWriter


class ReleaseService:
    def __init__(
        self,
        root: Path,
        database: Database,
        writer: WorkflowArtifactWriter,
    ) -> None:
        self.root = root
        self.database = database
        self.writer = writer

    def create_manifest(
        self,
        repo: ArtifactRepository,
        run_id: str,
    ) -> ArtifactEnvelope[ReleaseManifestData]:
        evidence = ArtifactEnvelope[EvidenceBundleData].model_validate(
            repo.read("07_evidence.yaml", ArtifactType.EVIDENCE_BUNDLE).model_dump(mode="json")
        )
        data = ReleaseManifestData(
            release_id=new_id("rel"),
            title=evidence.data.goal_title,
            status="ready" if _is_ready(evidence.data) else "blocked",
            git=self._git_state(evidence.data),
            safety=self._safety(evidence.data),
            local_commands=[
                f"coductor report {run_id}",
                f"coductor artifacts {run_id}",
                f"coductor logs {run_id} --tail 20",
            ],
            manual_commands=[
                "git diff --stat",
                "git status --short",
                "git add <reviewed-files>",
                'git commit -m "<message approved by human>"',
            ],
        )
        envelope = self.writer.envelope(
            run_id=run_id,
            artifact_type=ArtifactType.RELEASE_MANIFEST,
            artifact_id_prefix="art_release",
            status=(
                ArtifactStatus.READY
                if data.status == "ready"
                else ArtifactStatus.HUMAN_REQUIRED
            ),
            producer=Producer(kind=ProducerKind.SYSTEM, name="release-service"),
            inputs=[
                ArtifactInput.model_validate(
                    repo.input_for("07_evidence.yaml", evidence)
                )
            ],
            data=data,
        )
        repo.write("08_release_manifest.yaml", envelope)
        now = utc_now()
        self.database.add_event(run_id, "release", "release manifest generated by cli", now)
        return envelope

    def _git_state(self, evidence: EvidenceBundleData) -> ReleaseGitState:
        changed_files = _git_lines(self.root, ["status", "--short"])
        return ReleaseGitState(
            base_commit=evidence.base_commit,
            head_commit=evidence.head_commit,
            dirty_worktree=bool(changed_files),
            changed_files=changed_files,
        )

    def _safety(self, evidence: EvidenceBundleData) -> ReleaseSafety:
        reasons: list[str] = []
        if evidence.final_status != "ready_for_human_review":
            reasons.append(f"final_status is {evidence.final_status}")
        if not evidence.validation.valid:
            reasons.extend(evidence.validation.errors)
        ready = not reasons
        return ReleaseSafety(
            ready=ready,
            reasons=reasons,
            remote_actions_allowed=False,
        )


def _is_ready(evidence: EvidenceBundleData) -> bool:
    return evidence.final_status == "ready_for_human_review" and evidence.validation.valid


def _git_lines(root: Path, args: list[str]) -> list[str]:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
        )
    except OSError:
        return []
    if completed.returncode != 0:
        return []
    return [line for line in completed.stdout.splitlines() if line.strip()]
